---
relativeURLs: "true"
title: "Zenoh - The Zero Overhead, Pub/Sub, Store, Query, and Compute Protocol."
languageCode: "en-us"
canonifyURLs: "true"
pygmentsCodefences: true
pygmentsStyle: "manni"
googleAnalytics: G-PBD6MS51QL
enableRobotsTXT: true
enableEmoji: true
singleViewStyle: "caspertwo"

sitemap:
    changefreq: "weekly"
    priority: 0.5

menu:
  docs:
    - identifier: "overview"
      name: "Overview"
      weight: 1000
    - identifier: "getting_started"
      name: "Getting started"
      weight: 2000
    - identifier: "manual"
      name: "Reference manual"
      weight: 3000
    - identifier: "APIs"
      name: "API"
      weight: 4000
    - identifier: "migration_0.5_to_0.6"
      name: "Migration guides v0.5.x → v0.6.x"
      weight: 5000
    - identifier: "migration_1.0"
      name: "Migration guides v0.11. → v1.0 "
      weight: 6000
